### PR TITLE
add collection in lastEvent

### PR DESCRIPTION
**Pull request by preschian**
**Thank you for your contribution** to the [KodaDot Indexer](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring

### What's new?

- [x] add collection in lastEvent https://github.com/kodadot/nft-gallery/issues/3927#issue-1366497409

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've run the indexer and it hasn't failed
- [ ] I've changed schema and performed a migration
- [ ] I found edge cases

### Screenshot

- [x] My contribution is a **resolver** so I have pic from playground

Screen Shot 2022-09-09 at 21 54 14

### CODE REVIEW

**Comment by preschian** [comment]
first time to adjust indexer, is this the correct way to add collection in lastEvent query?
regarding this issue https://github.com/kodadot/nft-gallery/issues/3927#issue-1366497409

**Review by roiLeo — APPROVED** [review]
code looks good

Have you tested it locally?

**Comment by preschian** [comment]
> Have you tested it locally?

yes, I provide the screenshot. that was from my localhost

**Comment by roiLeo** [comment]
> yes, I provide the screenshot. that was from my localhost

is it normal that `collectionName` value is the same as `name`?

**Pull request merged**
