### PR TITLE
🔧 lastEvent check collection name not null

### PR DESCRIPTION
**Pull request by roiLeo**
**Thank you for your contribution** to the [KodaDot Indexer](https://kodadot.xyz).
👇 \_ Let's make a quick check before the contribution.

### PR type

- [x] Bugfix

### What's new?

- [ ] PR closes #<issue_number>
- [x] This PR is required for kodadot/nft-gallery#4123

### Before submitting Pull Request, please make sure:

- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've run the indexer and it hasn't failed
- [x] I've changed schema and performed a migration
- [ ] I found edge cases

### Screenshot

**before**
Capture d’écran 2022-10-17 à 4 27 55 PM

**after**
Capture d’écran 2022-10-17 à 4 27 50 PM

### CODE REVIEW

**Comment by yangwao** [comment]
@vikiival 👀

**Comment by KngZhi** [comment]
Should we also check why we had null collection name on db? It is optional on SNEK chain?

**Comment by vikiival** [comment]
@roiLeo may this? 

fb7638e208189a299e693d3a9266ec9c999a1c7c

**Comment by roiLeo** [comment]
> @roiLeo may this?
> 
> [fb7638e](https://github.com/kodadot/snek/commit/fb7638e208189a299e693d3a9266ec9c999a1c7c)

How can this be nullable if we have access to collectionId (`LEFT JOIN collection_entity ce on ne.collection_id = ce.id`)? something wrong with query?

**Comment by vikiival** [comment]
> How can this be nullable if we have access to collectionId

Because our pinata can for some unknown reasons timeout.

Also @brano-hozza opened a PR for IPFS race https://github.com/kodadot/packages/pull/54 that could help

**Comment by yangwao** [comment]
hypothetically.. is this related?
- https://github.com/kodadot/nft-gallery/issues/4132

**Review by vikiival — APPROVED** [review]

**Pull request merged**
