### PR TITLE
✨ series resolver

### PR DESCRIPTION
**Pull request by roiLeo**
yolo

### PR type

- [x] Feature

### What's new?

- [x] PR ref #3
- [x] This PR is required for kodadot/nft-gallery#3654

### Before submitting Pull Request, please make sure:

- [x] Didn't test
- [x] My contribution builds **clean without any errors or warnings**
- [x] I've merged recent default branch -- **main** and I've no conflicts
- [x] I've tried to respect high code quality standards
- [x] I've didn't break any original functionality
- [x] I've posted a screenshot of demonstrated change in this PR

### Optional

- [x] I've run the indexer and it hasn't failed
- [x] I've changed schema and performed a migration
- [ ] I found edge cases

### Screenshot

Capture d’écran 2022-09-14 à 9 31 50 AM

### CODE REVIEW

**Review by vikiival — CHANGES_REQUESTED** [review]
You are missing `cache.ts`

`Series` entity is filled by that

**Comment by roiLeo** [comment]
If I'm going to use `Series` resolver I won't be able to change dateRange (24H, 7D, 30D)
Any idea how we can calculate dailyVolume, weeklyVolume within the query?

**Review by vikiival — CHANGES_REQUESTED** [review]
pls do not use `pnpm` it will break on prod

**Comment by vikiival** [comment]
> My contribution is a resolver so I have pic from playground

Please can you run it on your machine for a couple of mins (10) to make sure it wont break op prod ?

**Review by vikiival — COMMENTED** [review]
CODE LOOKS LGTM

**Comment by roiLeo** [comment]
> Please can you run it on your machine for a couple of mins (10) to make sure it wont break op prod ?

This will be hard, last time I tried it ate all my mac's resources

pacman

**Comment by roiLeo** [comment]
> Please can you run it on your machine for a couple of mins (10) to make sure it wont break op prod ?

@vikiival after running it for about 1 hour, I still got empty array for Series resolver, seriesInsightTable looks like working.

Note: we should write somewhere in readme that you need to run `npm run build` when updating resolver in order to see the changes

**Comment by vikiival** [comment]
Can we resolve conflicts 🥺

**Comment by vikiival** [comment]
YOLO ❤️

**Pull request merged**
